name: m4d_core
description: Material Design 4 Dart
version: 0.2.2
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/m4d_core

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  # intl: ^0.15.0
  validate: ^1.0.0

  platform_detect: "^1.3.0"
  # browser_detect: ^1.0.0

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: ^1.0.0

  path: ^1.4.0

  l10n: ^2.0.0
    # path: /Volumes/Daten/DevLocal/DevDart/L10N4Dart

dev_dependencies:
  test: any

  build_runner: any
  build_test: any
  build_web_compilers: any
    
  args: any
